/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.bordermap;

import editor.handler.MapEditorHandler;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import tileset.NormalsNotFoundException;
import tileset.TextureNotFoundException;
import tileset.Tile;

/**
 *
 * @author Trifindo
 */
public class BorderMapsDisplay extends javax.swing.JPanel {

    private static final int mapSize = 32;
    private static final Color backgroundColor = new Color(0.0f, 0.5f, 0.5f, 1.0f);
    private static final Color borderColor = new Color(1.0f, 1.0f, 1.0f, 1.0f);

    private MapEditorHandler handler;

    /**
     * Creates new form MapBorderDisplay
     */
    public BorderMapsDisplay() {
        initComponents();

        setPreferredSize(new Dimension(BorderMapsGrid.cols * mapSize,
                BorderMapsGrid.rows * mapSize));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        int x = evt.getX() / mapSize;
        int y = BorderMapsGrid.cols - 1 - evt.getY() / mapSize;

        if (new Rectangle(BorderMapsGrid.cols, BorderMapsGrid.rows).contains(x, y) && !(x == 1 && y == 1)) {
            if (SwingUtilities.isLeftMouseButton(evt)) {
                final JFileChooser fc = new JFileChooser();
                if (handler.getLastTilesetDirectoryUsed() != null) {
                    fc.setCurrentDirectory(new File(handler.getLastTilesetDirectoryUsed()));
                }
                fc.setFileFilter(new FileNameExtensionFilter("OBJ (*.obj)", "obj"));
                fc.setApproveButtonText("Open");
                fc.setDialogTitle("Open");
                int returnVal = fc.showOpenDialog(handler.getMainFrame());
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    try {
                        handler.setLastTilesetDirectoryUsed(fc.getSelectedFile().getParent());
                        File file = fc.getSelectedFile();

                        handler.getBorderMapsGrid().grid[x][y] = handler.getBorderMapsTileset().getTiles().size();
                        for (int i = 0; i < handler.getBorderMapsTileset().size(); i++) {
                            if (!handler.getBorderMapsGrid().isTileInGrid(i)) {
                                handler.getBorderMapsTileset().removeTile(i);
                                handler.getBorderMapsGrid().decreaseFromIndex(i);
                                i--;
                            }
                        }
                        handler.getBorderMapsGrid().grid[x][y] = handler.getBorderMapsTileset().getTiles().size();
                        Tile tile = new Tile(handler.getBorderMapsTileset(), file.getAbsolutePath());
                        handler.getBorderMapsTileset().getTiles().add(tile);

                        System.out.println("Size border tileset: " + handler.getBorderMapsTileset().size());

                        //New code
                        handler.getBorderMapsTileset().removeUnusedTextures();
                        //handler.getMainFrame().getMapDisplay().requestBorderMapsUpdate();//REMOVED 
                        handler.getMainFrame().getMapDisplay().repaint();
                        handler.getMainFrame().getTileDisplay().requestUpdate();
                        handler.getMainFrame().getTileDisplay().repaint();

                        repaint();

                        System.out.println("border map loaded");

                    } catch (TextureNotFoundException ex) {
                        ex.printStackTrace();
                    } catch (NormalsNotFoundException ex) {
                        ex.printStackTrace();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            } else if (SwingUtilities.isRightMouseButton(evt)) {
                handler.getBorderMapsGrid().grid[x][y] = -1;

                //handler.getMainFrame().getMapDisplay().requestBorderMapsUpdate();
                handler.getMainFrame().getMapDisplay().repaint();

                repaint();
            }
        }

    }//GEN-LAST:event_formMousePressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        int x = evt.getX() / mapSize;
        int y = BorderMapsGrid.cols - 1 - evt.getY() / mapSize;
        if (new Rectangle(BorderMapsGrid.cols, BorderMapsGrid.rows).contains(x, y) && !(x == 1 && y == 1)) {
            this.setCursor(new Cursor(Cursor.HAND_CURSOR));
            this.setToolTipText("Open map");
        }else{
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            this.setToolTipText(null);
        }
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(2));
        for (int i = 0; i < BorderMapsGrid.cols; i++) {
            for (int j = 0; j < BorderMapsGrid.rows; j++) {
                g.setColor(backgroundColor);
                g.fillRect(i * mapSize, j * mapSize, mapSize, mapSize);

                g.setColor(borderColor);
                g.drawRect(i * mapSize, j * mapSize, mapSize, mapSize);
            }
        }

        g.setColor(Color.white);
        g.fillRect(1 * mapSize, 1 * mapSize, mapSize, mapSize);

        if (handler != null) {
            for (int i = 0; i < BorderMapsGrid.cols; i++) {
                for (int j = 0; j < BorderMapsGrid.rows; j++) {
                    g2.setStroke(new BasicStroke(1));
                    if (handler.getBorderMapsGrid().grid[i][j] != -1) {
                        g2.setColor(Color.green);
                        g.fillRect(i * mapSize, (BorderMapsGrid.cols - 1 - j) * mapSize, mapSize, mapSize);
                    }

                    g2.setStroke(new BasicStroke(2));
                    g2.setColor(borderColor);
                    g.drawRect(i * mapSize, (BorderMapsGrid.cols - 1 - j) * mapSize, mapSize, mapSize);
                }
            }
        }
    }

    public void init(MapEditorHandler handler) {
        this.handler = handler;
    }

}
