/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.imd;

import editor.handler.MapEditorHandler;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FilenameFilter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import utils.Utils;
import utils.swing.CheckboxListCellRenderer;
import utils.swing.JCheckboxList;

/**
 *
 * @author Trifindo
 */
public class ExportImdDialog extends javax.swing.JDialog {

    public static final int APPROVE_OPTION = 1, CANCEL_OPTION = 0;
    private int returnValue = CANCEL_OPTION;

    private String objFolderPath = "";
    private String imdFolderPath = "";
    private ArrayList<String> selectedObjNames = new ArrayList<>();

    private MapEditorHandler handler;

    /**
     * Creates new form ExportImdDialog
     */
    public ExportImdDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        getRootPane().setDefaultButton(jbAccept);
        jbAccept.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollCheckboxList = new utils.swing.JScrollCheckboxList();
        jLabel2 = new javax.swing.JLabel();
        jtfObjFolderPath = new javax.swing.JTextField();
        jbObjBrowse = new javax.swing.JButton();
        jbSelectAll = new javax.swing.JButton();
        jbDeselectAll = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jbAccept = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfImdFolderPath = new javax.swing.JTextField();
        jbImdBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export maps as IMD settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("OBJ settings"));

        jLabel1.setText("Select the OBJ maps that will be converted into IMD:");

        jScrollCheckboxList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollCheckboxList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel2.setText("OBJ folder path:");

        jtfObjFolderPath.setEditable(false);

        jbObjBrowse.setText("Browse...");
        jbObjBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObjBrowseActionPerformed(evt);
            }
        });

        jbSelectAll.setText("Select All");
        jbSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectAllActionPerformed(evt);
            }
        });

        jbDeselectAll.setText("Deselect All");
        jbDeselectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeselectAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollCheckboxList, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfObjFolderPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbObjBrowse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbSelectAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDeselectAll)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfObjFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbObjBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollCheckboxList, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSelectAll)
                    .addComponent(jbDeselectAll))
                .addContainerGap())
        );

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jbAccept.setText("OK");
        jbAccept.setPreferredSize(new java.awt.Dimension(65, 23));
        jbAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcceptActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("IMD settings"));

        jLabel3.setText("IMD destination folder path:");

        jtfImdFolderPath.setEditable(false);

        jbImdBrowse.setText("Browse...");
        jbImdBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImdBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfImdFolderPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbImdBrowse)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfImdFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImdBrowse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbObjBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObjBrowseActionPerformed
        final JFileChooser fc = new JFileChooser();
        File folder = new File(Utils.removeExtensionFromPath(handler.getMapMatrix().filePath)).getParentFile();
        fc.setCurrentDirectory(folder);
        //fc.setSelectedFile(folder);
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                try {
                    return f.isDirectory() || f.getName().endsWith(".obj");
                } catch (Exception ex) {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return "Folder or OBJ file (*.obj)";
            }
        });
        fc.setApproveButtonText("Select folder");
        fc.setDialogTitle("Select the folder that contains the OBJ files");

        int returnValOpen = fc.showOpenDialog(this);
        if (returnValOpen == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            if (file.exists()) {
                String folderPath;
                if (file.isDirectory()) {
                    folderPath = file.getPath();
                } else {
                    folderPath = file.getParent();
                }
                loadObjFilesFromFolder(folderPath);
            }
        }
    }//GEN-LAST:event_jbObjBrowseActionPerformed

    private void jbAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcceptActionPerformed
        if (!new File(objFolderPath).exists()) {
            JOptionPane.showMessageDialog(this,
                    "Please select a valid folder that contains the OBJ files.",
                    "Invalid OBJ folder",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!new File(imdFolderPath).exists()) {
            JOptionPane.showMessageDialog(this,
                    "Please select a valid output folder for exporting the IMD files.",
                    "Invalid IMD folder",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultListModel<JCheckBox> model = (DefaultListModel<JCheckBox>) jScrollCheckboxList.getCheckboxList().getModel();
            selectedObjNames = new ArrayList<>(model.getSize());
            for (int i = 0; i < model.getSize(); i++) {
                if (model.get(i).isSelected()) {
                    selectedObjNames.add(model.get(i).getText());
                }
            }
            if (selectedObjNames.size() > 0) {
                returnValue = APPROVE_OPTION;
                dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "There are no OBJ selected for converting into IMD.\n"
                        + "Select at least one OBJ model from the list.", "No OBJ models selected",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbAcceptActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        returnValue = CANCEL_OPTION;
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectAllActionPerformed
        DefaultListModel<JCheckBox> model = (DefaultListModel<JCheckBox>) jScrollCheckboxList.getCheckboxList().getModel();
        for (int i = 0; i < model.getSize(); i++) {
            model.get(i).setSelected(true);
        }
        jScrollCheckboxList.repaint();
    }//GEN-LAST:event_jbSelectAllActionPerformed

    private void jbDeselectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeselectAllActionPerformed
        DefaultListModel<JCheckBox> model = (DefaultListModel<JCheckBox>) jScrollCheckboxList.getCheckboxList().getModel();
        for (int i = 0; i < model.getSize(); i++) {
            model.get(i).setSelected(false);
        }
        jScrollCheckboxList.repaint();
    }//GEN-LAST:event_jbDeselectAllActionPerformed

    private void jbImdBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImdBrowseActionPerformed
        final JFileChooser fc = new JFileChooser();
        File folder = new File(Utils.removeExtensionFromPath(handler.getMapMatrix().filePath)).getParentFile();
        fc.setCurrentDirectory(folder);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setApproveButtonText("Select folder");
        fc.setDialogTitle("Select the folder for exporting the IMD files");

        int returnValOpen = fc.showOpenDialog(this);
        if (returnValOpen == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            if (file.exists() && file.isDirectory()) {
                imdFolderPath = file.getPath();
                jtfImdFolderPath.setText(imdFolderPath);
            }
        }
    }//GEN-LAST:event_jbImdBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private utils.swing.JScrollCheckboxList jScrollCheckboxList;
    private javax.swing.JButton jbAccept;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbDeselectAll;
    private javax.swing.JButton jbImdBrowse;
    private javax.swing.JButton jbObjBrowse;
    private javax.swing.JButton jbSelectAll;
    private javax.swing.JTextField jtfImdFolderPath;
    private javax.swing.JTextField jtfObjFolderPath;
    // End of variables declaration//GEN-END:variables

    public void init(MapEditorHandler handler) {
        this.handler = handler;

        String objFolderPath = new File(handler.getMapMatrix().filePath).getParent();
        loadObjFilesFromFolder(objFolderPath);

        String imdFolderPath = new File(Utils.removeExtensionFromPath(handler.getMapMatrix().filePath)).getParent();
        if (isFolderPathValid(imdFolderPath)) {
            this.imdFolderPath = imdFolderPath;
            jtfImdFolderPath.setText(imdFolderPath);
        }

    }

    private boolean isFolderPathValid(String folderPath) {
        try {
            File file = new File(folderPath);
            return file.isDirectory();
        } catch (Exception ex) {
            return false;
        }
    }

    private void loadObjFilesFromFolder(String folderPath) {
        try {
            File folder = new File(folderPath);
            File[] files = folder.listFiles(new FilenameFilter() {
                @Override
                public boolean accept(File dir, String name) {
                    return name.endsWith(".obj");
                }
            });

            DefaultListModel<JCheckBox> model = new DefaultListModel();
            this.jScrollCheckboxList.getCheckboxList().setModel(model);
            for (File file : files) {
                model.addElement(new JCheckBox(file.getName()));
            }

            for (int i = 0; i < model.getSize(); i++) {
                model.get(i).setSelected(hasMatrixCoordsInObjName(model.get(i).getText()));
            }
            jScrollCheckboxList.getCheckboxList().setModel(model);

            objFolderPath = folderPath;
            jtfObjFolderPath.setText(folderPath);
        } catch (Exception ex) {

        }
    }

    private boolean hasMatrixCoordsInObjName(String imdName) {
        String name = Utils.removeExtensionFromPath(imdName);
        try {
            String[] splitName = name.split("_");
            return (hasCoordInName(splitName[splitName.length - 2])
                    && hasCoordInName(splitName[splitName.length - 1]));
        } catch (Exception ex) {
            return false;
        }
    }

    private boolean hasCoordInName(String name) {
        try {
            Integer.parseInt(name);
            return true;
        } catch (Exception ex) {
            return false;
        }
    }

    /*
    private boolean hasMatrixCoordsInObjName(String objName) {
        String name = Utils.removeExtensionFromPath(objName);
        try {
            String[] splitName = name.split("_");
            return (hasCoordInName(splitName[splitName.length - 2], "X")
                    && hasCoordInName(splitName[splitName.length - 1], "Y"));
        } catch (Exception ex) {
            return false;
        }
    }

    private boolean hasCoordInName(String name, String coordChar) {
        try {
            Integer.parseInt(name.substring(1));
            return name.startsWith(coordChar);
        } catch (Exception ex) {
            return false;
        }
    }*/

    public int getReturnValue() {
        return returnValue;
    }

    public String getObjFolderPath() {
        return objFolderPath;
    }

    public String getImdFolderPath() {
        return imdFolderPath;
    }

    public ArrayList<String> getSelectedObjNames() {
        return selectedObjNames;
    }

}
