/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.buildingeditor;

import javax.swing.JOptionPane;

/**
 *
 * @author Trifindo
 */
public class BuildingMaterialRequestDialog extends javax.swing.JDialog {

    public static final int ACEPTED = 0, CANCELED = 1;
    private int returnValue = CANCELED;
    private int value = 0;
    private int min = 1;
    private int max = 20;
    private boolean useUndefined = false;

    /**
     * Creates new form IntegerRequestDialog
     */
    public BuildingMaterialRequestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbAccept = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jbCancel = new javax.swing.JButton();
        jcbUndefined = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Number of materials for the Building: ");

        jbAccept.setText("Accept");
        jbAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcceptActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jcbUndefined.setText("Undefined");
        jcbUndefined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUndefinedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAccept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbUndefined)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUndefined))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAccept)
                    .addComponent(jbCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcceptActionPerformed
        if (useUndefined) {
            returnValue = ACEPTED;
            dispose();
        } else {
            try {
                value = Integer.parseInt(jTextField1.getText());
                if (value >= min && value <= max) {
                    returnValue = ACEPTED;
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "The number must be inside the bounds ["
                            + String.valueOf(min) + ", "
                            + String.valueOf(max) + "]",
                            "Number is out of bounds",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "The number must be a integer",
                        "Error converting number",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jbAcceptActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        returnValue = CANCELED;
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jcbUndefinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUndefinedActionPerformed
        jTextField1.setEnabled(!jcbUndefined.isSelected());
        useUndefined = jcbUndefined.isSelected();
    }//GEN-LAST:event_jcbUndefinedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAccept;
    private javax.swing.JButton jbCancel;
    private javax.swing.JCheckBox jcbUndefined;
    // End of variables declaration//GEN-END:variables

    public void init(String msg, int min, int max) {
        this.jLabel1.setText(msg);
        this.min = min;
        this.max = max;

        this.jTextField1.setText(String.valueOf(value));
    }

    public int getIntegerRequested() {
        return value;
    }

    public boolean useUndefined() {
        return useUndefined;
    }

    public int getReturnValue() {
        return returnValue;
    }
}
