/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.bdhc;

import editor.handler.MapEditorHandler;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Stroke;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.SwingUtilities;

/**
 *
 * @author Trifindo
 */
public class BdhcDisplay extends javax.swing.JPanel {

    private MapEditorHandler handler;
    private BufferedImage mapImage;
    private BdhcHandler bdhcHandler;

    private static final int tileSize = 16;
    private static final int cols = 32, rows = 32;
    private static final int width = cols * tileSize, height = rows * tileSize;
    private static final int plateMargin = 3;
    private static final int cornerSize = 5;

    private static final int CORNER_NW = 6;
    private static final int CORNER_NE = 7;
    private static final int CORNER_SW = 4;
    private static final int CORNER_SE = 5;
    private static final int BORDER_N = 8;
    private static final int BORDER_S = 9;
    private static final int BORDER_W = 10;
    private static final int BORDER_E = 11;
    private static final int CENTER = 13;

    private int partHovering = -1;
    private int indexPlateHovering = -1;
    private int partSelected = -1;
    //private int indexPlateSelected = 0;
    //private int lastIndexPlateSelected = -1;
    private boolean dragging = false;
    private int lastPlateX, lastPlateY;
    private int lastPlateWidth, lastPlateHeight;
    private int lastX, lastY;

    /**
     * Creates new form BdhcDisplay
     */
    public BdhcDisplay() {
        initComponents();

        setPreferredSize(new Dimension(width, height));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        int x = getFixedMouseX(evt);
        int y = getFixedMouseY(evt);
        if (isHoveringPlate(bdhcHandler.getSelectedPlate(), x, y)) {
            partHovering = getPartSelected(bdhcHandler.getSelectedPlate(), x, y);
            indexPlateHovering = bdhcHandler.getSelectedPlateIndex();
            setCursor(new Cursor(partHovering));
        } else {
            for (int i = 0; i < bdhcHandler.getBdhc().getPlates().size(); i++) {
                Plate p = bdhcHandler.getBdhc().getPlate(i);
                if (isHoveringPlate(p, x, y)) {
                    partHovering = getPartSelected(p, x, y);
                    indexPlateHovering = i;
                    setCursor(new Cursor(partHovering));
                    return;
                }
            }
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            partHovering = -1;
            indexPlateHovering = -1;
        }
    }//GEN-LAST:event_formMouseMoved

    private void formMousePressed(MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        int x = getFixedMouseX(evt);
        int y = getFixedMouseY(evt);
        if (indexPlateHovering != -1) {
            if (SwingUtilities.isLeftMouseButton(evt)) {
                if (isHoveringPlate(bdhcHandler.getSelectedPlate(), x, y)) {
                    partSelected = getPartSelected(bdhcHandler.getSelectedPlate(), x, y);
                } else {
                    bdhcHandler.setSelectedPlate(indexPlateHovering);
                    partSelected = partHovering;
                }

                dragging = true;
                lastX = getFixedMouseX(evt);
                lastY = getFixedMouseY(evt);

                Plate p = bdhcHandler.getSelectedPlate();
                lastPlateX = p.x;
                lastPlateY = p.y;
                lastPlateWidth = p.width;
                lastPlateHeight = p.height;

                bdhcHandler.getDialog().updateView();
            }
            repaint();
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = getFixedMouseX(evt);
        int y = getFixedMouseY(evt);
        if (dragging && isCursorInsiePanel(evt)) {
            Plate p = bdhcHandler.getSelectedPlate();
            int deltaX = (x - lastX) / tileSize;
            int deltaY = (y - lastY) / tileSize;
            switch (partSelected) {
                case CENTER:
                    updatePlate(p, lastPlateX + deltaX, lastPlateY + deltaY, p.width, p.height);
                    break;
                case CORNER_SE:
                    updatePlate(p, p.x, p.y, lastPlateWidth + deltaX, lastPlateHeight + deltaY);
                    break;
                case CORNER_NW:
                    updatePlate(p, lastPlateX + deltaX, lastPlateY + deltaY, lastPlateWidth - deltaX, lastPlateHeight - deltaY);
                    break;
                case CORNER_NE:
                    updatePlate(p, p.x, lastPlateY + deltaY, lastPlateWidth + deltaX, lastPlateHeight - deltaY);
                    break;
                case CORNER_SW:
                    updatePlate(p, lastPlateX + deltaX, p.y, lastPlateWidth - deltaX, lastPlateHeight + deltaY);
                    break;
                case BORDER_N:
                    updatePlate(p, p.x, lastPlateY + deltaY, p.width, lastPlateHeight - deltaY);
                    break;
                case BORDER_S:
                    updatePlate(p, p.x, p.y, p.width, lastPlateHeight + deltaY);
                    break;
                case BORDER_W:
                    updatePlate(p, lastPlateX + deltaX, p.y, lastPlateWidth - deltaX, p.height);
                    break;
                case BORDER_E:
                    updatePlate(p, p.x, p.y, lastPlateWidth + deltaX, p.height);
                    break;
            }
            repaint();
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        dragging = false;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        int wheelRotation = evt.getWheelRotation();
        if (wheelRotation > 0) {
            bdhcHandler.getSelectedPlate().z--;
        } else if (wheelRotation < 0) {
            bdhcHandler.getSelectedPlate().z++;
        }
        bdhcHandler.getDialog().updateView();
    }//GEN-LAST:event_formMouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (mapImage != null && handler != null && bdhcHandler != null) {
            Bdhc bdhc = bdhcHandler.getBdhc();

            Graphics2D g2d = (Graphics2D) g;

            g2d.scale((float) getWidth() / width, (float) getHeight() / height);

            g.drawImage(mapImage, 0, 0, null);

            g.setColor(new Color(255, 255, 255, 100));
            drawGrid(g);

            g2d.setStroke(new BasicStroke(4));
            g.setColor(Color.red);
            g.drawLine(width / 2, height / 2, width, height / 2);
            g.setColor(Color.green);
            g.drawLine(width / 2, height / 2, width / 2, height);
            g.setColor(Color.blue);
            g.drawLine(width / 2, height / 2, width / 2, width / 2);

            g.translate(width / 2, height / 2);
            drawPlates(g, bdhc);

            g.translate(-width / 2, -height / 2);

            g2d.scale((float) width / getWidth(), (float) height / getHeight());
        }
    }

    private void drawPlates(Graphics g, Bdhc bdhc) {

        for (int i = 0; i < bdhc.getPlates().size(); i++) {
            g.setColor(bdhc.getPlate(i).getColor());
            fillPlate(g, bdhc.getPlate(i));
            drawPlateIndex(g, bdhc.getPlate(i), i);
        }
        /*
        for (int i = 0; i < bdhcHandler.getSelectedPlateIndex(); i++) {
            g.setColor(bdhc.getPlate(i).getColor());
            fillPlate(g, bdhc.getPlate(i));
            drawPlateIndex(g, bdhc.getPlate(i), i);
        }
        g.setColor(Plate.selectedColor);
        fillPlate(g, bdhcHandler.getSelectedPlate());
        drawPlateIndex(g, bdhcHandler.getSelectedPlate(), bdhcHandler.getSelectedPlateIndex());
        for (int i = bdhcHandler.getSelectedPlateIndex() + 1; i < bdhc.getPlates().size(); i++) {
            g.setColor(bdhc.getPlate(i).getColor());
            fillPlate(g, bdhc.getPlate(i));
            drawPlateIndex(g, bdhc.getPlate(i), i);
        }
         */
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(3));
        for (int i = 0; i < bdhc.getPlates().size(); i++) {
            g.setColor(bdhc.getPlate(i).getBorderColor());//g.setColor(Color.blue);
            drawPlateBorder(g, bdhc.getPlates().get(i));
        }

        g.setColor(Color.red);
        drawPlateBorder(g, bdhcHandler.getSelectedPlate());
    }

    public void updatePlate(Plate p, int c, int r, int width, int height) {
        int xMin = -16;
        int xMax = 16;
        int yMin = -16;
        int yMax = 16;

        int newX = Math.min(Math.max(c, xMin), xMax - width);
        int newY = Math.min(Math.max(r, yMin), yMax - height);

        if (width > 0 && height > 0) {
            p.x = newX;
            p.y = newY;
            p.width = width;
            p.height = height;
        }
    }

    public int getPartSelected(Plate p, int x, int y) {
        if (new Rectangle(
                p.x * tileSize + width / 2,
                p.y * tileSize + height / 2,
                cornerSize,
                cornerSize
        ).contains(x, y)) {
            return CORNER_NW;
        }

        if (new Rectangle(
                (p.x + p.width) * tileSize + width / 2 - cornerSize,
                p.y * tileSize + height / 2,
                cornerSize,
                cornerSize
        ).contains(x, y)) {
            return CORNER_NE;
        }

        if (new Rectangle(
                p.x * tileSize + width / 2,
                (p.y + p.height) * tileSize + height / 2 - cornerSize,
                cornerSize,
                cornerSize
        ).contains(x, y)) {
            return CORNER_SW;
        }

        if (new Rectangle(
                (p.x + p.width) * tileSize + width / 2 - cornerSize,
                (p.y + p.height) * tileSize + height / 2 - cornerSize,
                cornerSize,
                cornerSize
        ).contains(x, y)) {
            return CORNER_SE;
        }

        if (y < p.y * tileSize + height / 2 + cornerSize) {
            return BORDER_N;
        }
        if (y > (p.y + p.height) * tileSize + height / 2 - cornerSize) {
            return BORDER_S;
        }
        if (x < p.x * tileSize + width / 2 + cornerSize) {
            return BORDER_W;
        }
        if (x > (p.x + p.width) * tileSize + width / 2 - cornerSize) {
            return BORDER_E;
        }

        return CENTER;
    }

    public boolean isCursorInsiePanel(MouseEvent evt) {
        int x = getFixedMouseX(evt);
        int y = getFixedMouseY(evt);
        if (x < 0 || x >= width || y < 0 || y >= height) {
            return false;
        }
        return true;
    }

    public boolean isHoveringPlate(Plate p, int x, int y) {
        return new Rectangle(
                p.x * tileSize + width / 2,
                p.y * tileSize + height / 2,
                p.width * tileSize,
                p.height * tileSize
        ).contains(x, y);
    }

    private void drawPlateBorder(Graphics g, Plate p) {
        g.drawRect(p.x * tileSize, p.y * tileSize,
                p.width * tileSize - 1, p.height * tileSize - 1);
    }

    private void fillPlate(Graphics g, Plate p) {
        g.fillRect(p.x * tileSize, p.y * tileSize,
                p.width * tileSize, p.height * tileSize);

    }

    private void drawPlateIndex(Graphics g, Plate p, int index) {
        g.setColor(Color.white);
        g.drawString(
                String.valueOf(index), p.x * tileSize + 4, p.y * tileSize + 12);
    }

    private void drawGrid(Graphics g) {
        for (int i = 0; i < width; i++) {
            g.drawLine(i * tileSize, 0, i * tileSize, height);
        }

        for (int i = 0; i < height; i++) {
            g.drawLine(0, i * tileSize, width, i * tileSize);
        }
    }

    public void init(MapEditorHandler handler, BufferedImage mapImage, BdhcHandler bdhcHandler) {
        this.handler = handler;
        this.mapImage = mapImage;
        this.bdhcHandler = bdhcHandler;
    }

    private int getFixedMouseX(MouseEvent evt) {
        return (int) (evt.getX() * ((float) width / getWidth()));
    }

    private int getFixedMouseY(MouseEvent evt) {
        return (int) (evt.getY() * ((float) height / getHeight()));
    }

}
