/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.vertexcolors;

import editor.handler.MapEditorHandler;
import editor.tileseteditor.TilesetEditorHandler;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.DocumentFilter.FilterBypass;
import tileset.TileGeometryCompresser;
import utils.Utils;
import utils.Utils.MutableBoolean;

/**
 *
 * @author Trifindo
 */
public class VColorEditorDialog extends javax.swing.JDialog {

    private MapEditorHandler handler;
    private TilesetEditorHandler tsetHandler;

    private MutableBoolean jtfRedEnabled = new MutableBoolean(true);
    private MutableBoolean jtfGreenEnabled = new MutableBoolean(true);
    private MutableBoolean jtfBlueEnabled = new MutableBoolean(true);

    private String allVertexModeDescription = "Use left click for painting vertices. "
            + "Use mouse wheel for rotating the model. ";
    private String perFaceModeDescription = "Use right click for selecting a face. "
            + "Use left click for painting the vertices of the selected face. "
            + "Use the mouse wheel for rotating the model. ";
    private String grabColorModeDescription = "Use left click for selecting the vertex and taking its color. "
            + "Use the mouse wheel for rotating the model. ";

    /**
     * Creates new form VertexColorEditorDialog
     */
    public VColorEditorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        addListenersToJTextField(jtfRed, jtfRedEnabled);
        addListenersToJTextField(jtfGreen, jtfGreenEnabled);
        addListenersToJTextField(jtfBlue, jtfBlueEnabled);

        jtaModeDescription.setText(allVertexModeDescription);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vColorEditorDisplay1 = new VColorEditorDisplay();
        jPanel2 = new javax.swing.JPanel();
        colorWheelPanel1 = new ColorWheelPanel();
        colorBrightnessPanel1 = new ColorBrightnessPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfRed = new JTextField();
        jtfGreen = new JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfBlue = new JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbVertexMode = new javax.swing.JButton();
        jbFaceMode = new javax.swing.JButton();
        jbGrabColor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbSolidView = new javax.swing.JButton();
        jbTextureView = new javax.swing.JButton();
        jbWireframeView = new javax.swing.JButton();
        jbSimpleView = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaModeDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vertex Color Editor");

        vColorEditorDisplay1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout vColorEditorDisplay1Layout = new javax.swing.GroupLayout(vColorEditorDisplay1);
        vColorEditorDisplay1.setLayout(vColorEditorDisplay1Layout);
        vColorEditorDisplay1Layout.setHorizontalGroup(
            vColorEditorDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        vColorEditorDisplay1Layout.setVerticalGroup(
            vColorEditorDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Brush Color"));

        colorWheelPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                colorWheelPanel1MouseDragged(evt);
            }
        });
        colorWheelPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                colorWheelPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout colorWheelPanel1Layout = new javax.swing.GroupLayout(colorWheelPanel1);
        colorWheelPanel1.setLayout(colorWheelPanel1Layout);
        colorWheelPanel1Layout.setHorizontalGroup(
            colorWheelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );
        colorWheelPanel1Layout.setVerticalGroup(
            colorWheelPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        colorBrightnessPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                colorBrightnessPanel1MouseDragged(evt);
            }
        });
        colorBrightnessPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                colorBrightnessPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout colorBrightnessPanel1Layout = new javax.swing.GroupLayout(colorBrightnessPanel1);
        colorBrightnessPanel1.setLayout(colorBrightnessPanel1Layout);
        colorBrightnessPanel1Layout.setHorizontalGroup(
            colorBrightnessPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        colorBrightnessPanel1Layout.setVerticalGroup(
            colorBrightnessPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new Color(255, 0, 0));
        jLabel1.setText("R:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new Color(0, 153, 0));
        jLabel2.setText("G:");

        jtfRed.setText("255");

        jtfGreen.setText("255");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new Color(0, 0, 204));
        jLabel3.setText("B:");

        jtfBlue.setText("255");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(colorWheelPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorBrightnessPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfRed, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorBrightnessPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorWheelPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Modes"));

        jbVertexMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/VertexSelectionIcon.png"))); // NOI18N
        jbVertexMode.setText("All Vertex Mode");
        jbVertexMode.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbVertexModeActionPerformed(evt);
            }
        });

        jbFaceMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FaceSelectionIcon.png"))); // NOI18N
        jbFaceMode.setText("Per Face Mode");
        jbFaceMode.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbFaceModeActionPerformed(evt);
            }
        });

        jbGrabColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GrabColorIcon.png"))); // NOI18N
        jbGrabColor.setText("Grab Vertex Color");
        jbGrabColor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbGrabColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbVertexMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbFaceMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGrabColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVertexMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFaceMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGrabColor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("View Modes"));

        jbSolidView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SolidViewIcon.png"))); // NOI18N
        jbSolidView.setText("Solid View");
        jbSolidView.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbSolidViewActionPerformed(evt);
            }
        });

        jbTextureView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TextureViewIcon.png"))); // NOI18N
        jbTextureView.setText("Texture View");
        jbTextureView.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbTextureViewActionPerformed(evt);
            }
        });

        jbWireframeView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/WireframeViewIcon.png"))); // NOI18N
        jbWireframeView.setText("Wireframe View");
        jbWireframeView.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbWireframeViewActionPerformed(evt);
            }
        });

        jbSimpleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/NoWireframeViewIcon.png"))); // NOI18N
        jbSimpleView.setText("Simple View");
        jbSimpleView.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbSimpleViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTextureView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSolidView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbWireframeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSimpleView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSolidView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTextureView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbWireframeView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSimpleView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Brush Size"));

        jSlider1.setMinimum(5);
        jSlider1.setValue(20);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Mode Description"));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtaModeDescription.setColumns(20);
        jtaModeDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaModeDescription.setLineWrap(true);
        jtaModeDescription.setRows(5);
        jtaModeDescription.setWrapStyleWord(true);
        jtaModeDescription.setDisabledTextColor(new Color(51, 51, 51));
        jtaModeDescription.setEnabled(false);
        jScrollPane1.setViewportView(jtaModeDescription);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vColorEditorDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vColorEditorDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorWheelPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorWheelPanel1MousePressed
        Color selectedColor = colorWheelPanel1.getSelectedColor();
        tsetHandler.setLastColorUsed(selectedColor);
        jPanel1.setBackground(selectedColor);
        updateViewTextFieldsRGB(selectedColor);
        jPanel1.repaint();
    }//GEN-LAST:event_colorWheelPanel1MousePressed

    private void colorWheelPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorWheelPanel1MouseDragged
        Color selectedColor = colorWheelPanel1.getSelectedColor();
        tsetHandler.setLastColorUsed(selectedColor);
        jPanel1.setBackground(selectedColor);
        updateViewTextFieldsRGB(selectedColor);
        jPanel1.repaint();
    }//GEN-LAST:event_colorWheelPanel1MouseDragged

    private void colorBrightnessPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBrightnessPanel1MousePressed
        colorWheelPanel1.setBrightness(colorBrightnessPanel1.getBrightness());
        colorWheelPanel1.updateImage();
        colorWheelPanel1.repaint();

        Color selectedColor = colorWheelPanel1.getSelectedColor();
        tsetHandler.setLastColorUsed(selectedColor);
        jPanel1.setBackground(selectedColor);
        updateViewTextFieldsRGB(selectedColor);
        jPanel1.repaint();
    }//GEN-LAST:event_colorBrightnessPanel1MousePressed

    private void colorBrightnessPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBrightnessPanel1MouseDragged
        colorWheelPanel1.setBrightness(colorBrightnessPanel1.getBrightness());
        colorWheelPanel1.updateImage();
        colorWheelPanel1.repaint();

        Color selectedColor = colorWheelPanel1.getSelectedColor();
        tsetHandler.setLastColorUsed(selectedColor);
        jPanel1.setBackground(selectedColor);
        updateViewTextFieldsRGB(selectedColor);
        jPanel1.repaint();
    }//GEN-LAST:event_colorBrightnessPanel1MouseDragged

    private void jbVertexModeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbVertexModeActionPerformed
        vColorEditorDisplay1.setSelectionMode(VColorEditorDisplay.BRUSH_MODE);
        vColorEditorDisplay1.repaint();

        jtaModeDescription.setText(allVertexModeDescription);
    }//GEN-LAST:event_jbVertexModeActionPerformed

    private void jbFaceModeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbFaceModeActionPerformed
        vColorEditorDisplay1.setSelectionMode(VColorEditorDisplay.POLYGON_SELECTION_MODE);
        vColorEditorDisplay1.repaint();

        jtaModeDescription.setText(perFaceModeDescription);
    }//GEN-LAST:event_jbFaceModeActionPerformed

    private void jbSolidViewActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbSolidViewActionPerformed
        vColorEditorDisplay1.setDrawTextures(false);
        vColorEditorDisplay1.repaint();
    }//GEN-LAST:event_jbSolidViewActionPerformed

    private void jbTextureViewActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbTextureViewActionPerformed
        vColorEditorDisplay1.setDrawTextures(true);
        vColorEditorDisplay1.repaint();
    }//GEN-LAST:event_jbTextureViewActionPerformed

    private void jbWireframeViewActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbWireframeViewActionPerformed
        vColorEditorDisplay1.setWireframe(true);
        vColorEditorDisplay1.repaint();
    }//GEN-LAST:event_jbWireframeViewActionPerformed

    private void jbSimpleViewActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbSimpleViewActionPerformed
        vColorEditorDisplay1.setWireframe(false);
        vColorEditorDisplay1.repaint();
    }//GEN-LAST:event_jbSimpleViewActionPerformed

    private void jbGrabColorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbGrabColorActionPerformed
        vColorEditorDisplay1.setSelectionMode(VColorEditorDisplay.COLOR_GRAB_MODE);
        vColorEditorDisplay1.repaint();

        jtaModeDescription.setText(grabColorModeDescription);
    }//GEN-LAST:event_jbGrabColorActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        vColorEditorDisplay1.setBrushSize(jSlider1.getValue());
        vColorEditorDisplay1.repaint();
    }//GEN-LAST:event_jSlider1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ColorBrightnessPanel colorBrightnessPanel1;
    private ColorWheelPanel colorWheelPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton jbFaceMode;
    private javax.swing.JButton jbGrabColor;
    private javax.swing.JButton jbSimpleView;
    private javax.swing.JButton jbSolidView;
    private javax.swing.JButton jbTextureView;
    private javax.swing.JButton jbVertexMode;
    private javax.swing.JButton jbWireframeView;
    private javax.swing.JTextArea jtaModeDescription;
    private JTextField jtfBlue;
    private JTextField jtfGreen;
    private JTextField jtfRed;
    private VColorEditorDisplay vColorEditorDisplay1;
    // End of variables declaration//GEN-END:variables

    public void init(MapEditorHandler handler, TilesetEditorHandler tsetHandler) {
        this.handler = handler;
        this.tsetHandler = tsetHandler;
        this.vColorEditorDisplay1.setHandler(handler, tsetHandler, this);

        setSelectedColor(tsetHandler.getLastColorUsed());
    }

    public Color getSelectedColor() {
        return colorWheelPanel1.getSelectedColor();
    }

    public void updateViewTextFieldsRGB(Color color) {
        jtfRedEnabled.value = false;
        jtfGreenEnabled.value = false;
        jtfBlueEnabled.value = false;
        jtfRed.setText(String.valueOf(color.getRed()));
        jtfGreen.setText(String.valueOf(color.getGreen()));
        jtfBlue.setText(String.valueOf(color.getBlue()));
        jtfRedEnabled.value = true;
        jtfGreenEnabled.value = true;
        jtfBlueEnabled.value = true;
    }

    public void setSelectedColor(Color color) {
        float[] hsv = Color.RGBtoHSB(color.getRed(), color.getGreen(), color.getBlue(), null);
        colorWheelPanel1.setColor(color);
        colorWheelPanel1.updateImage();
        colorBrightnessPanel1.setBrightness(hsv[2]);
        jPanel1.setBackground(color);

        tsetHandler.setLastColorUsed(color);

        updateViewTextFieldsRGB(color);
        colorWheelPanel1.repaint();
        colorBrightnessPanel1.repaint();
        jPanel1.repaint();

    }

    private Color getColorFromJTextFields() {
        int r = getColorComponentFromJTextField(jtfRed);
        int g = getColorComponentFromJTextField(jtfGreen);
        int b = getColorComponentFromJTextField(jtfBlue);
        return new Color(r, g, b);
    }

    private int getColorComponentFromJTextField(JTextField jtf) {
        int value;
        try {
            value = Integer.parseInt(jtf.getText());
        } catch (NumberFormatException ex) {
            value = 0;
        }
        if (value < 0) {
            value = 0;
        } else if (value > 255) {
            value = 255;
        }
        return value;
    }

    private void fixJTextFieldValue(JTextField jtf, MutableBoolean enabled) {
        enabled.value = false;
        jtf.setText(String.valueOf(getColorComponentFromJTextField(jtf)));
        enabled.value = true;
    }

    private void addListenersToJTextField(JTextField jtf, MutableBoolean enabled) {
        ((AbstractDocument) jtf.getDocument()).setDocumentFilter(new DocumentFilter() {
            Pattern regEx = Pattern.compile("\\d*");

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                Matcher matcher = regEx.matcher(text);
                if (!matcher.matches()) {
                    return;
                }
                super.replace(fb, offset, length, text, attrs);
            }
        });

        jtf.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                update();
            }

            public void removeUpdate(DocumentEvent e) {
                update();
            }

            public void insertUpdate(DocumentEvent e) {
                update();
            }

            public void update() {
                if (enabled.value) {
                    Color color = getColorFromJTextFields();
                    float[] hsv = Color.RGBtoHSB(color.getRed(), color.getGreen(), color.getBlue(), null);
                    colorWheelPanel1.setColor(color);
                    colorWheelPanel1.updateImage();
                    colorBrightnessPanel1.setBrightness(hsv[2]);
                    jPanel1.setBackground(color);

                    tsetHandler.setLastColorUsed(color);

                    colorWheelPanel1.repaint();
                    colorBrightnessPanel1.repaint();
                    jPanel1.repaint();
                }
            }
        });

        jtf.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                fixJTextFieldValue(jtf, enabled);
            }
        });

        jtf.addFocusListener(new java.awt.event.FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                fixJTextFieldValue(jtf, enabled);
            }
        });
    }
}
