/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor.mapmatrix;

import editor.handler.MapEditorHandler;
import editor.state.MapLayerState;
import java.awt.Point;

/**
 *
 * @author Trifindo
 */
public class MoveMapPanel extends javax.swing.JPanel {

    private MapEditorHandler handler;
    
    /**
     * Creates new form MoveMapPanel
     */
    public MoveMapPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbUp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbLeft = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbRight = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jbDown = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        add(jPanel1);

        jbUp.setText("▲");
        jbUp.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpActionPerformed(evt);
            }
        });
        add(jbUp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        add(jPanel2);

        jbLeft.setText("◄");
        jbLeft.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLeftActionPerformed(evt);
            }
        });
        add(jbLeft);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        add(jPanel3);

        jbRight.setText("►");
        jbRight.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRightActionPerformed(evt);
            }
        });
        add(jbRight);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        add(jPanel5);

        jbDown.setText("▼");
        jbDown.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDownActionPerformed(evt);
            }
        });
        add(jbDown);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents

    private void jbUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpActionPerformed
        moveMap(handler.getMapSelected(), new Point(0, -1));
    }//GEN-LAST:event_jbUpActionPerformed

    private void jbDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDownActionPerformed
        moveMap(handler.getMapSelected(), new Point(0, 1));
    }//GEN-LAST:event_jbDownActionPerformed

    private void jbLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLeftActionPerformed
        moveMap(handler.getMapSelected(), new Point(-1, 0));
    }//GEN-LAST:event_jbLeftActionPerformed

    private void jbRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRightActionPerformed
        moveMap(handler.getMapSelected(), new Point(1, 0));
    }//GEN-LAST:event_jbRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbDown;
    private javax.swing.JButton jbLeft;
    private javax.swing.JButton jbRight;
    private javax.swing.JButton jbUp;
    // End of variables declaration//GEN-END:variables

    public void init(MapEditorHandler handler){
        this.handler = handler;
    }
    
    public void moveMap(Point p, Point dp){
        //handler.setLayerChanged(false);
        //handler.addMapState(new MapLayerState("Map moved", handler));
        
        Point newCoords =  new Point(p.x + dp.x, p.y + dp.y);
        handler.getMapMatrix().moveMap(p, newCoords);
        
        handler.setMapSelected(newCoords);
        //handler.getMainFrame().getMapDisplay().setCameraAtSelectedMap();
        handler.getMainFrame().getMapDisplay().repaint();
        
        handler.getMapMatrix().updateBordersData();
        handler.getMainFrame().updateMapMatrixDisplay();
        
        
    }

}
